# Generated by Django 5.2.5 on 2025-08-13 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_employee_email_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contract_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('system_size', models.CharField(blank=True, max_length=50, null=True)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
                ('redline', models.CharField(blank=True, max_length=50, null=True)),
                ('closer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.employee')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('Clawback', 'Clawback')], max_length=8)),
                ('paying_date', models.DateField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.employee')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.order')),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts',
                'db_table': 'payouts',
            },
        ),
    ]
